# Generated by Django 2.2.7 on 2019-12-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=3, max_digits=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
